name: Pylint

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install pylint
        python setup.py install
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=C0111,R0902,R0913,W0718,C0121,W0201,R0903,C0301,W0707,R0914,R0912,C0103,R1710,R0911,W0719,R1720,E1101,R0801,R1705,R0904 --good-names=i,e,cg,t,s
